#!/system/bin/sh
#Code by @chamchamfy
[ "$(uname -o)" = "GNU/Linux" ] && root=sudo || unset root
[ -d /sdcard ] && dulieu=/sdcard || dulieu=$HOME
ur=$dulieu/.ur
libcc=$ur/libcc
bins=$ur/bins 
bina=$ur/bin
binx64=$ur/binx64
binc=$PREFIX/toolcc/bin
apktoolcc=$ur/cc/apktoolcc
toolcc=$PREFIX/toolcc
opcc=$ur/cc/opcc
libtoolcc=$ur/cc/libtoolcc
for t in $ur $bins $bina $libcc $apktoolcc $binc $opcc $libtoolcc; do $root mkdir -p $t 2>/dev/null; done 
if [ "$(uname -o)" = "GNU/Linux" ]; then 
sudo chmod -R 777 $HOME
dulieu=$HOME
ur=$dulieu/.ur
echo -n " + Cập nhật dữ liệu ban đầu (c/k): "; read aa
if [ "$aa" = "c" ]; then 
(
sudo apt-get update >/dev/null
sudo apt-get install openjdk-21-jdk-headless shc curl zip unzip zstd binutils e2fsprogs erofs-utils android-sdk-libsparse-utils zipalign python3 python3-pip util-linux bsdmainutils f2fs-tools p7zip -y >/dev/null
sudo rm -f /usr/lib/python*/EXTERNALLY-MANAGED 2>/dev/null
pip3 install protobuf bsdiff4 six crypto construct google docopt pycryptodome zstandard >/dev/null
echo "protobuf<=3.20.1" > requirements.txt
pip3 install -r requirements.txt >/dev/null;
)
fi
[ ! -f $libcc/urtoolcc_wsl.zip ] && $root curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/urtoolcc_wsl.zip -o $libcc/urtoolcc_wsl.zip 2>/dev/null 
[ -f $libcc/urtoolcc_wsl.zip ] && $root unzip -qo $libcc/urtoolcc_wsl.zip -d $ur 2>/dev/null 
[ ! -f $libcc/apktoolcc.so ] && $root curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/apktoolcc.so -o $libcc/apktoolcc.so 2>/dev/null 
[ -f $libcc/apktoolcc.so ] && $root tar -xJf $libcc/apktoolcc.so -C $apktoolcc 2>/dev/null 
[ ! -f $libcc/opcc.so ] && $root curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/opcc.so -o $libcc/opcc.so 2>/dev/null 
[ -f $libcc/opcc.so ] && $root tar -xJf $libcc/opcc.so -C $opcc 2>/dev/null 
[ ! -f $libcc/b.zip ] && $root curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/b.zip -o $libcc/b.zip 2>/dev/null 
[ -f $libcc/b.zip ] && $root unzip -qo $libcc/b.zip -d $ur 2>/dev/null 
$root curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/apktool.jar -o $apktoolcc/lib/apktoolc.jar 2>/dev/null 
$root cp -af $binx64/* /usr/bin 2>/dev/null
$root chmod +x /usr/bin/* 2>/dev/null
$root cp -af $apktoolcc/* $toolcc 2>/dev/null
$root chmod -R 775 $toolcc 2>/dev/null
$root cp -af $binx64/* $binc 2>/dev/null 
$root chmod +x $binc/* 2>/dev/null 
echo " + Xong."; 
else
echo -n " + Cập nhật dữ liệu ban đầu (c/k): "; read aa
if [ "$aa" = "c" ]; then 
(
termux-setup-storage -y
pkg update -y && pkg upgrade -y && pkg install which brotli curl zip unzip zstd pzstd binutils android-tools shc clang proot e2fsprogs python3 openjdk-17 p7zip -y && pkg update -y && pkg upgrade -y
pip3 install protobuf bsdiff4 six crypto construct google docopt pycryptodome zstandard
)
fi
echo
echo -n " + Xoá dữ liệu cũ (c/k): "; read k; 
if [ "$k" = "c" ]; then echo " + Đang xoá..."; rm -f $libcc/* 2>/dev/null && echo " + Xong!"; else echo " + Bỏ qua !"; fi 
echo -n " + Tải dữ liệu mới (c/k): "; read k; 
if [ "$k" = "c" ]; then echo " + Đang cập nhật..."; 
[ ! -f $libcc/bin.so ] && curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/bin.so -o $libcc/bin.so 2>/dev/null 
[ ! -f $libcc/bin.so ] && curl -L# https://sourceforge.net/projects/chamchamfy/files/Tools/bin.so -o $libcc/bin.so 2>/dev/null 
[ -f $libcc/bin.so ] && tar -xJf $libcc/bin.so -C $ur 2>/dev/null 
[ ! -f $libcc/apktoolcc.so ] && curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/apktoolcc.so -o $libcc/apktoolcc.so 2>/dev/null 
[ -f $libcc/apktoolcc.so ] && tar -xJf $libcc/apktoolcc.so -C $apktoolcc 2>/dev/null 
[ ! -f $libcc/opcc.so ] && curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/opcc.so -o $libcc/opcc.so 2>/dev/null 
[ -f $libcc/opcc.so ] && tar -xJf $libcc/opcc.so -C $opcc 2>/dev/null 
[ ! -f $libcc/b.zip ] && curl -L# https://raw.githubusercontent.com/chamchamfy/toolcc/main/b.zip -o $libcc/b.zip 2>/dev/null 
[ -f $libcc/b.zip ] && unzip -qo $libcc/b.zip -d $ur 2>/dev/null 
else echo " + Bỏ qua !"
fi 

cp -af $bins/* $bina 2>/dev/null 
cp -af $apktoolcc/* $libtoolcc 2>/dev/null 
cp -af $bina $libtoolcc 2>/dev/null 

cp -af $apktoolcc/* $toolcc 2>/dev/null
chmod -R 775 $toolcc 2>/dev/null
cp -af $bina/* $binc 2>/dev/null 
chmod +x $binc/* 2>/dev/null 
cp -af $bina/* $PATH 2>/dev/null 
chmod +x $PATH/* 2>/dev/null 
echo " + Xong."; 
fi 
exit 
