name: 'BUILD OVERLAY'
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: 'Xem quá trình...'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: 'Xem thông báo'
        run: |
          chmod 777 .github/* 2>/dev/null 
          export NG="$(date +"%y%m%d")"
          echo "PB=$NG" >> $GITHUB_ENV
          .github/Reo 2>&1 | tee -a log.txt

      - uses: actions/upload-artifact@v5
        with:
          name: overlay.zip
          path: signed/*

      - name: Overlay
        run: |
          if gh release view Overlay_V1.${{ env.PB }} >/dev/null 2>&1; then
            gh release upload Overlay_V1.${{ env.PB }} OV/* --clobber
          else
            gh release create Overlay_V1.${{ env.PB }} OV/* \
              --prerelease \
              --title "Overlay V1.${{ env.PB }}" \
              --notes "Release Overlay build ${{ env.PB }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Flash Overlay
        run: |
          if gh release view VH_XIAOMI_TWRP_V1.${{ env.PB }} >/dev/null 2>&1; then
            gh release upload VH_XIAOMI_TWRP_V1.${{ env.PB }} UP/* --clobber
          else
            gh release create VH_XIAOMI_TWRP_V1.${{ env.PB }} UP/* \
              --prerelease \
              --title "VH_XIAOMI_TWRP V1.${{ env.PB }}" \
              --notes "Flash Overlay build ${{ env.PB }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lưu Log
        uses: actions/upload-artifact@v5
        with:
          name: Xem Log
          path: log.txt
          retention-days: 30
